project:
  type: website

website:
  title: "Jyoti Ranjan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact
format:
  html:
    theme: cosmo
    toc: false
