project:
  type: website

website:
  title: "Jyoti Ranjan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/tell2jyoti
      - icon: linkedin
        href: https://www.linkedin.com/in/jyoti-ranjan-panda-0667645/

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: false
    css: styles.css
    mainfont: "system-ui, -apple-system, sans-serif"
    page-layout: article
    max-width: 900px
